/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.scinti.lfr.secpg.sqlinjection.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import it.scinti.lfr.secpg.sqlinjection.model.Vendor;
import it.scinti.lfr.secpg.sqlinjection.model.VendorModel;
import it.scinti.lfr.secpg.sqlinjection.model.VendorSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Vendor service. Represents a row in the &quot;sqlj_Vendor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VendorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VendorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VendorImpl
 * @see Vendor
 * @see VendorModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class VendorModelImpl extends BaseModelImpl<Vendor>
	implements VendorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vendor model instance should use the {@link Vendor} interface instead.
	 */
	public static final String TABLE_NAME = "sqlj_Vendor";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "vendorId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "hwId", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "website", Types.VARCHAR },
			{ "metadata", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vendorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hwId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("website", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("metadata", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table sqlj_Vendor (uuid_ VARCHAR(75) null,vendorId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,hwId VARCHAR(75) null,name VARCHAR(75) null,description VARCHAR(75) null,website VARCHAR(75) null,metadata VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table sqlj_Vendor";
	public static final String ORDER_BY_JPQL = " ORDER BY vendor.vendorId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sqlj_Vendor.vendorId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(it.scinti.lfr.secpg.sqlinjection.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.it.scinti.lfr.secpg.sqlinjection.model.Vendor"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(it.scinti.lfr.secpg.sqlinjection.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.it.scinti.lfr.secpg.sqlinjection.model.Vendor"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(it.scinti.lfr.secpg.sqlinjection.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.scinti.lfr.secpg.sqlinjection.model.Vendor"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long DESCRIPTION_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long HWID_COLUMN_BITMASK = 8L;
	public static final long METADATA_COLUMN_BITMASK = 16L;
	public static final long NAME_COLUMN_BITMASK = 32L;
	public static final long UUID_COLUMN_BITMASK = 64L;
	public static final long WEBSITE_COLUMN_BITMASK = 128L;
	public static final long VENDORID_COLUMN_BITMASK = 256L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Vendor toModel(VendorSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Vendor model = new VendorImpl();

		model.setUuid(soapModel.getUuid());
		model.setVendorId(soapModel.getVendorId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setHwId(soapModel.getHwId());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setWebsite(soapModel.getWebsite());
		model.setMetadata(soapModel.getMetadata());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Vendor> toModels(VendorSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Vendor> models = new ArrayList<Vendor>(soapModels.length);

		for (VendorSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(it.scinti.lfr.secpg.sqlinjection.service.util.ServiceProps.get(
				"lock.expiration.time.it.scinti.lfr.secpg.sqlinjection.model.Vendor"));

	public VendorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _vendorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVendorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _vendorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Vendor.class;
	}

	@Override
	public String getModelClassName() {
		return Vendor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("vendorId", getVendorId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("hwId", getHwId());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("website", getWebsite());
		attributes.put("metadata", getMetadata());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long vendorId = (Long)attributes.get("vendorId");

		if (vendorId != null) {
			setVendorId(vendorId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String hwId = (String)attributes.get("hwId");

		if (hwId != null) {
			setHwId(hwId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String website = (String)attributes.get("website");

		if (website != null) {
			setWebsite(website);
		}

		String metadata = (String)attributes.get("metadata");

		if (metadata != null) {
			setMetadata(metadata);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getVendorId() {
		return _vendorId;
	}

	@Override
	public void setVendorId(long vendorId) {
		_columnBitmask = -1L;

		_vendorId = vendorId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getHwId() {
		if (_hwId == null) {
			return "";
		}
		else {
			return _hwId;
		}
	}

	@Override
	public void setHwId(String hwId) {
		_columnBitmask |= HWID_COLUMN_BITMASK;

		if (_originalHwId == null) {
			_originalHwId = _hwId;
		}

		_hwId = hwId;
	}

	public String getOriginalHwId() {
		return GetterUtil.getString(_originalHwId);
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_columnBitmask |= DESCRIPTION_COLUMN_BITMASK;

		if (_originalDescription == null) {
			_originalDescription = _description;
		}

		_description = description;
	}

	public String getOriginalDescription() {
		return GetterUtil.getString(_originalDescription);
	}

	@JSON
	@Override
	public String getWebsite() {
		if (_website == null) {
			return "";
		}
		else {
			return _website;
		}
	}

	@Override
	public void setWebsite(String website) {
		_columnBitmask |= WEBSITE_COLUMN_BITMASK;

		if (_originalWebsite == null) {
			_originalWebsite = _website;
		}

		_website = website;
	}

	public String getOriginalWebsite() {
		return GetterUtil.getString(_originalWebsite);
	}

	@JSON
	@Override
	public String getMetadata() {
		if (_metadata == null) {
			return "";
		}
		else {
			return _metadata;
		}
	}

	@Override
	public void setMetadata(String metadata) {
		_columnBitmask |= METADATA_COLUMN_BITMASK;

		if (_originalMetadata == null) {
			_originalMetadata = _metadata;
		}

		_metadata = metadata;
	}

	public String getOriginalMetadata() {
		return GetterUtil.getString(_originalMetadata);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Vendor.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Vendor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Vendor toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Vendor)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VendorImpl vendorImpl = new VendorImpl();

		vendorImpl.setUuid(getUuid());
		vendorImpl.setVendorId(getVendorId());
		vendorImpl.setGroupId(getGroupId());
		vendorImpl.setCompanyId(getCompanyId());
		vendorImpl.setUserId(getUserId());
		vendorImpl.setUserName(getUserName());
		vendorImpl.setCreateDate(getCreateDate());
		vendorImpl.setModifiedDate(getModifiedDate());
		vendorImpl.setHwId(getHwId());
		vendorImpl.setName(getName());
		vendorImpl.setDescription(getDescription());
		vendorImpl.setWebsite(getWebsite());
		vendorImpl.setMetadata(getMetadata());

		vendorImpl.resetOriginalValues();

		return vendorImpl;
	}

	@Override
	public int compareTo(Vendor vendor) {
		int value = 0;

		if (getVendorId() < vendor.getVendorId()) {
			value = -1;
		}
		else if (getVendorId() > vendor.getVendorId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Vendor)) {
			return false;
		}

		Vendor vendor = (Vendor)obj;

		long primaryKey = vendor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VendorModelImpl vendorModelImpl = this;

		vendorModelImpl._originalUuid = vendorModelImpl._uuid;

		vendorModelImpl._originalGroupId = vendorModelImpl._groupId;

		vendorModelImpl._setOriginalGroupId = false;

		vendorModelImpl._originalCompanyId = vendorModelImpl._companyId;

		vendorModelImpl._setOriginalCompanyId = false;

		vendorModelImpl._setModifiedDate = false;

		vendorModelImpl._originalHwId = vendorModelImpl._hwId;

		vendorModelImpl._originalName = vendorModelImpl._name;

		vendorModelImpl._originalDescription = vendorModelImpl._description;

		vendorModelImpl._originalWebsite = vendorModelImpl._website;

		vendorModelImpl._originalMetadata = vendorModelImpl._metadata;

		vendorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Vendor> toCacheModel() {
		VendorCacheModel vendorCacheModel = new VendorCacheModel();

		vendorCacheModel.uuid = getUuid();

		String uuid = vendorCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			vendorCacheModel.uuid = null;
		}

		vendorCacheModel.vendorId = getVendorId();

		vendorCacheModel.groupId = getGroupId();

		vendorCacheModel.companyId = getCompanyId();

		vendorCacheModel.userId = getUserId();

		vendorCacheModel.userName = getUserName();

		String userName = vendorCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			vendorCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			vendorCacheModel.createDate = createDate.getTime();
		}
		else {
			vendorCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			vendorCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			vendorCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		vendorCacheModel.hwId = getHwId();

		String hwId = vendorCacheModel.hwId;

		if ((hwId != null) && (hwId.length() == 0)) {
			vendorCacheModel.hwId = null;
		}

		vendorCacheModel.name = getName();

		String name = vendorCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			vendorCacheModel.name = null;
		}

		vendorCacheModel.description = getDescription();

		String description = vendorCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			vendorCacheModel.description = null;
		}

		vendorCacheModel.website = getWebsite();

		String website = vendorCacheModel.website;

		if ((website != null) && (website.length() == 0)) {
			vendorCacheModel.website = null;
		}

		vendorCacheModel.metadata = getMetadata();

		String metadata = vendorCacheModel.metadata;

		if ((metadata != null) && (metadata.length() == 0)) {
			vendorCacheModel.metadata = null;
		}

		return vendorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", vendorId=");
		sb.append(getVendorId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", hwId=");
		sb.append(getHwId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", website=");
		sb.append(getWebsite());
		sb.append(", metadata=");
		sb.append(getMetadata());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("it.scinti.lfr.secpg.sqlinjection.model.Vendor");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vendorId</column-name><column-value><![CDATA[");
		sb.append(getVendorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hwId</column-name><column-value><![CDATA[");
		sb.append(getHwId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>website</column-name><column-value><![CDATA[");
		sb.append(getWebsite());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>metadata</column-name><column-value><![CDATA[");
		sb.append(getMetadata());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Vendor.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Vendor.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _vendorId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _hwId;
	private String _originalHwId;
	private String _name;
	private String _originalName;
	private String _description;
	private String _originalDescription;
	private String _website;
	private String _originalWebsite;
	private String _metadata;
	private String _originalMetadata;
	private long _columnBitmask;
	private Vendor _escapedModel;
}