/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.scinti.lfr.secpg.sqlinjection.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Vendor service. Represents a row in the &quot;sqlj_Vendor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.scinti.lfr.secpg.sqlinjection.model.impl.VendorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.scinti.lfr.secpg.sqlinjection.model.impl.VendorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vendor
 * @see it.scinti.lfr.secpg.sqlinjection.model.impl.VendorImpl
 * @see it.scinti.lfr.secpg.sqlinjection.model.impl.VendorModelImpl
 * @generated
 */
@ProviderType
public interface VendorModel extends BaseModel<Vendor>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vendor model instance should use the {@link Vendor} interface instead.
	 */

	/**
	 * Returns the primary key of this vendor.
	 *
	 * @return the primary key of this vendor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vendor.
	 *
	 * @param primaryKey the primary key of this vendor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this vendor.
	 *
	 * @return the uuid of this vendor
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this vendor.
	 *
	 * @param uuid the uuid of this vendor
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the vendor ID of this vendor.
	 *
	 * @return the vendor ID of this vendor
	 */
	public long getVendorId();

	/**
	 * Sets the vendor ID of this vendor.
	 *
	 * @param vendorId the vendor ID of this vendor
	 */
	public void setVendorId(long vendorId);

	/**
	 * Returns the group ID of this vendor.
	 *
	 * @return the group ID of this vendor
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vendor.
	 *
	 * @param groupId the group ID of this vendor
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vendor.
	 *
	 * @return the company ID of this vendor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vendor.
	 *
	 * @param companyId the company ID of this vendor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vendor.
	 *
	 * @return the user ID of this vendor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vendor.
	 *
	 * @param userId the user ID of this vendor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vendor.
	 *
	 * @return the user uuid of this vendor
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this vendor.
	 *
	 * @param userUuid the user uuid of this vendor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vendor.
	 *
	 * @return the user name of this vendor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vendor.
	 *
	 * @param userName the user name of this vendor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vendor.
	 *
	 * @return the create date of this vendor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vendor.
	 *
	 * @param createDate the create date of this vendor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vendor.
	 *
	 * @return the modified date of this vendor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vendor.
	 *
	 * @param modifiedDate the modified date of this vendor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the hw ID of this vendor.
	 *
	 * @return the hw ID of this vendor
	 */
	@AutoEscape
	public String getHwId();

	/**
	 * Sets the hw ID of this vendor.
	 *
	 * @param hwId the hw ID of this vendor
	 */
	public void setHwId(String hwId);

	/**
	 * Returns the name of this vendor.
	 *
	 * @return the name of this vendor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this vendor.
	 *
	 * @param name the name of this vendor
	 */
	public void setName(String name);

	/**
	 * Returns the description of this vendor.
	 *
	 * @return the description of this vendor
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vendor.
	 *
	 * @param description the description of this vendor
	 */
	public void setDescription(String description);

	/**
	 * Returns the website of this vendor.
	 *
	 * @return the website of this vendor
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this vendor.
	 *
	 * @param website the website of this vendor
	 */
	public void setWebsite(String website);

	/**
	 * Returns the metadata of this vendor.
	 *
	 * @return the metadata of this vendor
	 */
	@AutoEscape
	public String getMetadata();

	/**
	 * Sets the metadata of this vendor.
	 *
	 * @param metadata the metadata of this vendor
	 */
	public void setMetadata(String metadata);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Vendor vendor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Vendor> toCacheModel();

	@Override
	public Vendor toEscapedModel();

	@Override
	public Vendor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}